/*
 * The MIT License
 *
 * Copyright 2015 eziama.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE  
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 * Modified by Yufen Wang.
 * 2016
 */

package inf2b.algobench.ui;

import inf2b.algobench.main.AlgoBench;
import java.awt.CardLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.net.URL;

public class Help extends javax.swing.JDialog {

    /**
     * Creates new form Help
     *
     * @param parent
     * @param modal
     * @param url
     */
    public Help(java.awt.Frame parent, boolean modal, String url) {
        super(parent, modal);
        initComponents();
        CardLayout layout = (CardLayout) jPanelHelpBody.getLayout();
        layout.show(jPanelHelpBody, "cardLoading");

        // add listener for when the content finishes loading
        this.jEditorPaneHelpText.addPropertyChangeListener("page",
                new PropertyChangeListener() {

                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        layout.show(jPanelHelpBody, "cardHelpContent");
                    }
                });
        URL helpURL = getClass().getResource(url);
        if (helpURL != null) {
            try {
                this.jEditorPaneHelpText.setPage(helpURL);
                this.jEditorPaneHelpText.setEditable(false);
                this.revalidate();
            }
            catch (IOException e) {
                System.err.println("Bad help URL: " + helpURL);
            }
        }
        else {
            System.err.println("Couldn't find help file.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHelpBody = new javax.swing.JPanel();
        jScrollPaneHelp = new javax.swing.JScrollPane();
        jEditorPaneHelpText = new javax.swing.JEditorPane();
        jLabelLoading = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCloseHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        setIconImages(AlgoBench.iconImagesList);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanelHelpBody.setPreferredSize(new java.awt.Dimension(701, 480));
        jPanelHelpBody.setLayout(new java.awt.CardLayout());

        jEditorPaneHelpText.setEditable(false);
        jEditorPaneHelpText.setContentType("text/html"); // NOI18N
        jScrollPaneHelp.setViewportView(jEditorPaneHelpText);

        jPanelHelpBody.add(jScrollPaneHelp, "cardHelpContent");

        jLabelLoading.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLoading.setFont(jLabelLoading.getFont().deriveFont((float)13));
        jLabelLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoading.setText("Loading help content. Please wait...");
        jLabelLoading.setOpaque(true);
        jPanelHelpBody.add(jLabelLoading, "cardLoading");

        getContentPane().add(jPanelHelpBody, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(612, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jButtonCloseHelp.setText("Close");
        jButtonCloseHelp.setMaximumSize(new java.awt.Dimension(80, 23));
        jButtonCloseHelp.setMinimumSize(new java.awt.Dimension(80, 23));
        jButtonCloseHelp.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonCloseHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseHelpActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCloseHelp);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseHelpActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCloseHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseHelp;
    private javax.swing.JEditorPane jEditorPaneHelpText;
    private javax.swing.JLabel jLabelLoading;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelHelpBody;
    private javax.swing.JScrollPane jScrollPaneHelp;
    // End of variables declaration//GEN-END:variables
}
