/*
 * The MIT License
 *
 * Copyright 2015 Eziama Ubachukwu (eziama.ubachukwu@gmail.com).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package inf2b.algobench.ui.components;

import inf2b.algobench.util.ITaskSubPanel;

/**
 *
 * @author eziama ubachukwu
 */
public class GraphTaskSubPanel extends javax.swing.JPanel implements ITaskSubPanel {

    /**
     * Creates new form GraphTaskSubPanel
     */
    public GraphTaskSubPanel() {
        initComponents();
        
        // hide simulate-long-visit labels
        this.jLabelGraphIsDelayed.setVisible(false);
        this.jLabelLongVisitText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGraph = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabelCurrentGraphSize = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelGraphMemUsage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNumScheduledTasks = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNumCompletedTasks = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelPercentage = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabelGraphRepresentation = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelLongVisitText = new javax.swing.JLabel();
        jLabelGraphIsDelayed = new javax.swing.JLabel();
        jPanelDetailGraph = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabelGraphFixedParam = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabelGraphFixedValue = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelDirectedEdges = new javax.swing.JLabel();
        jLabelSelfLoop = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabelGraphIncrement = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabelGraphVariedParam = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabelGraphStartSize = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabelGraphFinalSize = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 0));

        jPanelGraph.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Execution Progress Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, jLabel30.getFont()));
        jPanelGraph.setOpaque(false);
        jPanelGraph.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(jLabel22.getFont().deriveFont((float)13));
        jLabel22.setText("Current no. of edges:");
        jPanelGraph.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 185, 20));

        jLabelCurrentGraphSize.setFont(jLabelCurrentGraphSize.getFont().deriveFont((float)13));
        jLabelCurrentGraphSize.setText("--");
        jPanelGraph.add(jLabelCurrentGraphSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 140, 20));

        jLabel25.setFont(jLabel25.getFont().deriveFont((float)13));
        jLabel25.setText("Memory footprint (estimate):");
        jLabel25.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel25.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel25.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 185, 20));

        jLabelGraphMemUsage.setFont(jLabelGraphMemUsage.getFont().deriveFont((float)13));
        jLabelGraphMemUsage.setForeground(new java.awt.Color(255, 0, 51));
        jLabelGraphMemUsage.setText("--");
        jPanelGraph.add(jLabelGraphMemUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 75, 140, 20));

        jLabel4.setFont(jLabel4.getFont().deriveFont((float)13));
        jLabel4.setText("No. of scheduled tasks:");
        jPanelGraph.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, 185, 20));

        jLabelNumScheduledTasks.setFont(jLabelNumScheduledTasks.getFont().deriveFont((float)13));
        jLabelNumScheduledTasks.setText("--");
        jPanelGraph.add(jLabelNumScheduledTasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 145, 140, 20));

        jLabel5.setFont(jLabel5.getFont().deriveFont((float)13));
        jLabel5.setText("No. of completed tasks:");
        jPanelGraph.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 185, 20));

        jLabelNumCompletedTasks.setFont(jLabelNumCompletedTasks.getFont().deriveFont((float)13));
        jLabelNumCompletedTasks.setText("--");
        jPanelGraph.add(jLabelNumCompletedTasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 140, 20));

        jLabel6.setFont(jLabel6.getFont().deriveFont((float)13));
        jLabel6.setText("Percentage completion:");
        jPanelGraph.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 215, 185, 20));

        jLabelPercentage.setFont(jLabelPercentage.getFont().deriveFont(jLabelPercentage.getFont().getStyle() | java.awt.Font.BOLD, 13));
        jLabelPercentage.setText("--");
        jPanelGraph.add(jLabelPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 215, 140, 20));

        jLabel32.setFont(jLabel32.getFont().deriveFont((float)13));
        jLabel32.setText("Graph representation:");
        jLabel32.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel32.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel32.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 185, 20));

        jLabelGraphRepresentation.setFont(jLabelGraphRepresentation.getFont().deriveFont((float)13));
        jLabelGraphRepresentation.setText("Adjacency List");
        jPanelGraph.add(jLabelGraphRepresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 140, 20));
        jPanelGraph.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, -1));

        jLabelLongVisitText.setFont(jLabelLongVisitText.getFont().deriveFont((float)13));
        jLabelLongVisitText.setText("Long visit simulated:");
        jLabelLongVisitText.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabelLongVisitText.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabelLongVisitText.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabelLongVisitText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 185, 20));

        jLabelGraphIsDelayed.setFont(jLabelGraphIsDelayed.getFont().deriveFont((float)13));
        jLabelGraphIsDelayed.setText("--");
        jPanelGraph.add(jLabelGraphIsDelayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 140, 20));

        add(jPanelGraph);

        jPanelDetailGraph.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Setup Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, jLabel30.getFont()));
        jPanelDetailGraph.setOpaque(false);
        jPanelDetailGraph.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(jLabel30.getFont().deriveFont((float)13));
        jLabel30.setText("Fixed parameter:");
        jLabel30.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel30.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel30.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 20));

        jLabelGraphFixedParam.setFont(jLabelGraphFixedParam.getFont().deriveFont((float)13));
        jLabelGraphFixedParam.setText("--");
        jPanelDetailGraph.add(jLabelGraphFixedParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 20));

        jLabel31.setFont(jLabel31.getFont().deriveFont((float)13));
        jLabel31.setText("Size:");
        jLabel31.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel31.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel31.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 150, 20));

        jLabelGraphFixedValue.setFont(jLabelGraphFixedValue.getFont().deriveFont((float)13));
        jLabelGraphFixedValue.setText("--");
        jPanelDetailGraph.add(jLabelGraphFixedValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 75, 150, 20));

        jLabel33.setFont(jLabel33.getFont().deriveFont((float)13));
        jLabel33.setText("Directed edges:");
        jLabel33.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel33.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel33.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 20));

        jLabelDirectedEdges.setFont(jLabelDirectedEdges.getFont().deriveFont((float)13));
        jLabelDirectedEdges.setText("--");
        jPanelDetailGraph.add(jLabelDirectedEdges, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 150, 20));

        jLabelSelfLoop.setFont(jLabelSelfLoop.getFont().deriveFont((float)13));
        jLabelSelfLoop.setText("--");
        jPanelDetailGraph.add(jLabelSelfLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 285, 150, 20));

        jLabel35.setFont(jLabel35.getFont().deriveFont((float)13));
        jLabel35.setText("Self-loop allowed:");
        jLabel35.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel35.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel35.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, 150, 20));

        jLabel37.setFont(jLabel37.getFont().deriveFont((float)13));
        jLabel37.setText("Start size:");
        jLabel37.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel37.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel37.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, 150, -1));

        jLabelGraphIncrement.setFont(jLabelGraphIncrement.getFont().deriveFont((float)13));
        jLabelGraphIncrement.setText("--");
        jPanelDetailGraph.add(jLabelGraphIncrement, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 20));

        jLabel38.setFont(jLabel38.getFont().deriveFont((float)13));
        jLabel38.setText("Varied Parameter:");
        jLabel38.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel38.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel38.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, -1));

        jLabelGraphVariedParam.setFont(jLabelGraphVariedParam.getFont().deriveFont((float)13));
        jLabelGraphVariedParam.setText("--");
        jPanelDetailGraph.add(jLabelGraphVariedParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 20));

        jLabel39.setFont(jLabel39.getFont().deriveFont((float)13));
        jLabel39.setText("Increment:");
        jLabel39.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel39.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel39.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, -1));

        jLabelGraphStartSize.setFont(jLabelGraphStartSize.getFont().deriveFont((float)13));
        jLabelGraphStartSize.setText("--");
        jPanelDetailGraph.add(jLabelGraphStartSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 145, 150, 20));

        jLabel34.setFont(jLabel34.getFont().deriveFont((float)13));
        jLabel34.setText("Final size:");
        jLabel34.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel34.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel34.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 215, 150, 20));

        jLabelGraphFinalSize.setFont(jLabelGraphFinalSize.getFont().deriveFont((float)13));
        jLabelGraphFinalSize.setText("--");
        jPanelDetailGraph.add(jLabelGraphFinalSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 215, 150, 20));

        add(jPanelDetailGraph);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setInputSize(String size) {

    }

    @Override
    public void setInitialSize(String startSize) {
        this.jLabelGraphStartSize.setText(startSize);
    }

    @Override
    public void setFinalSize(String startSize) {
        this.jLabelGraphFinalSize.setText(startSize);
    }
    @Override
    public void setMemUsage(String graphMemUsage) {
        this.jLabelGraphMemUsage.setText(graphMemUsage);
    }

    @Override
    public void setStepSize(String stepSize) {
        jLabelGraphIncrement.setText(stepSize);
    }

    @Override
    public void setNumCompletedTasks(String numCompletedTasks) {
        jLabelNumCompletedTasks.setText(numCompletedTasks);
        Integer p = Integer.parseInt(numCompletedTasks) * 100
                / Integer.parseInt(jLabelNumScheduledTasks.getText());
        jLabelPercentage.setText(p.toString() + "%");
    }

    @Override
    public void setNumTasks(String numTasks) {
        jLabelNumScheduledTasks.setText(numTasks);
    }

    @Override
    public void setCurrentSize(String currentGraphSize) {
        this.jLabelCurrentGraphSize.setText(currentGraphSize);
    }

    public void setHasDirectedEdges(String directedEdges) {
        this.jLabelDirectedEdges.setText(directedEdges);
    }

    public void setGraphFixedParam(String graphFixedParam) {
        if (graphFixedParam.toUpperCase().startsWith("V")) {
            this.jLabelGraphVariedParam.setText("EDGES");
            this.jLabelGraphFixedParam.setText("VERTICES");
        }
        else {
            this.jLabelGraphVariedParam.setText("VERTICES");
            this.jLabelGraphFixedParam.setText("EDGES");
        }
    }

    public void setGraphFixedValue(String graphFixedValue) {
        this.jLabelGraphFixedValue.setText(graphFixedValue);
    }
    
    public void setGraphIsDelayed(boolean graphIsDelayed) {
        this.jLabelGraphIsDelayed.setText(Boolean.toString(graphIsDelayed).toUpperCase());
    }

    public void setGraphRepresentation(String graphRepresentation) {
        this.jLabelGraphRepresentation.setText(graphRepresentation);
    }

    public void setAllowSelfLoop(String selfLoop) {
        this.jLabelSelfLoop.setText(selfLoop);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCurrentGraphSize;
    private javax.swing.JLabel jLabelDirectedEdges;
    private javax.swing.JLabel jLabelGraphFinalSize;
    private javax.swing.JLabel jLabelGraphFixedParam;
    private javax.swing.JLabel jLabelGraphFixedValue;
    private javax.swing.JLabel jLabelGraphIncrement;
    private javax.swing.JLabel jLabelGraphIsDelayed;
    private javax.swing.JLabel jLabelGraphMemUsage;
    private javax.swing.JLabel jLabelGraphRepresentation;
    private javax.swing.JLabel jLabelGraphStartSize;
    private javax.swing.JLabel jLabelGraphVariedParam;
    private javax.swing.JLabel jLabelLongVisitText;
    private javax.swing.JLabel jLabelNumCompletedTasks;
    private javax.swing.JLabel jLabelNumScheduledTasks;
    private javax.swing.JLabel jLabelPercentage;
    private javax.swing.JLabel jLabelSelfLoop;
    private javax.swing.JPanel jPanelDetailGraph;
    private javax.swing.JPanel jPanelGraph;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
