
/*
 * The MIT License
 *
 * Copyright 2015 Eziama Ubachukwu (eziama.ubachukwu@gmail.com).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 * Modified by Yufen Wang.
 * 2016
 */

package inf2b.algobench.ui.components;

import inf2b.algobench.util.ITaskSubPanel;

/**
 *
 * @author eziama ubachukwu and Yufen Wang
 */
public class HashTaskSubPanel extends javax.swing.JPanel implements ITaskSubPanel {

    /**
     * Creates new form GraphTaskSubPanel
     */
    public HashTaskSubPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGraph = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabelMemUsage = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelMinBucketSize = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabelMaxBucketSize = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabeAverageBucketSize = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelBucketSizeSD = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelBucketSizeRange = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelDetailGraph = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabelInputSize = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelBucketArraySize = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabelHashFunction = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabelHashKeyType = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 0));

        jPanelGraph.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Execution Progress Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, jLabelBucketArraySize.getFont()));
        jPanelGraph.setOpaque(false);
        jPanelGraph.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(jLabel24.getFont().deriveFont((float)13));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Bucket memory footprint:");
        jLabel24.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel24.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel24.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 185, 20));

        jLabelMemUsage.setFont(jLabelMemUsage.getFont().deriveFont((float)13));
        jLabelMemUsage.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMemUsage.setText("--");
        jPanelGraph.add(jLabelMemUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 180, 20));

        jLabel25.setFont(jLabel25.getFont().deriveFont((float)13));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Min. bucket size:");
        jLabel25.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel25.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel25.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 185, 20));

        jLabelMinBucketSize.setFont(jLabelMinBucketSize.getFont().deriveFont((float)13));
        jLabelMinBucketSize.setText("--");
        jPanelGraph.add(jLabelMinBucketSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 180, 20));

        jLabel27.setFont(jLabel27.getFont().deriveFont((float)13));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Max. bucket size:");
        jLabel27.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel27.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel27.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 185, 20));

        jLabelMaxBucketSize.setFont(jLabelMaxBucketSize.getFont().deriveFont((float)13));
        jLabelMaxBucketSize.setText("--");
        jPanelGraph.add(jLabelMaxBucketSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 75, 180, 20));

        jLabel26.setFont(jLabel26.getFont().deriveFont((float)13));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Average bucket size:");
        jLabel26.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel26.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel26.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 185, 20));

        jLabeAverageBucketSize.setFont(jLabeAverageBucketSize.getFont().deriveFont((float)13));
        jLabeAverageBucketSize.setText("--");
        jPanelGraph.add(jLabeAverageBucketSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, 20));

        jLabel28.setFont(jLabel28.getFont().deriveFont((float)13));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Standard deviation:");
        jLabel28.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel28.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel28.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 185, 20));

        jLabelBucketSizeSD.setFont(jLabelBucketSizeSD.getFont().deriveFont((float)13));
        jLabelBucketSizeSD.setText("--");
        jPanelGraph.add(jLabelBucketSizeSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, 20));

        jLabel29.setFont(jLabel29.getFont().deriveFont((float)13));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Range:");
        jLabel29.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel29.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel29.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelGraph.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 185, 20));

        jLabelBucketSizeRange.setFont(jLabelBucketSizeRange.getFont().deriveFont((float)13));
        jLabelBucketSizeRange.setText("--");
        jPanelGraph.add(jLabelBucketSizeRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, 20));
        jPanelGraph.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 270, 10));

        add(jPanelGraph);

        jPanelDetailGraph.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Setup Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, jLabelInputSize.getFont()));
        jPanelDetailGraph.setOpaque(false);
        jPanelDetailGraph.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(jLabel30.getFont().deriveFont((float)13));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Total no. of elements:");
        jLabel30.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel30.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel30.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 20));

        jLabelInputSize.setFont(jLabelInputSize.getFont().deriveFont((float)13));
        jLabelInputSize.setText("--");
        jPanelDetailGraph.add(jLabelInputSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 160, 20));

        jLabel22.setFont(jLabel22.getFont().deriveFont((float)13));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Bucket array size:");
        jPanelDetailGraph.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, 160, 20));

        jLabelBucketArraySize.setFont(jLabelBucketArraySize.getFont().deriveFont((float)13));
        jLabelBucketArraySize.setText("--");
        jPanelDetailGraph.add(jLabelBucketArraySize, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 75, 150, 20));

        jLabel34.setFont(jLabel34.getFont().deriveFont((float)13));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Hash function:");
        jLabel34.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel34.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel34.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabelHashFunction.setFont(jLabelHashFunction.getFont().deriveFont((float)13));
        jLabelHashFunction.setText("--");
        jPanelDetailGraph.add(jLabelHashFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 20));

        jLabel36.setFont(jLabel36.getFont().deriveFont((float)13));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Hash key type:");
        jLabel36.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel36.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel36.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanelDetailGraph.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, -1, -1));

        jLabelHashKeyType.setFont(jLabelHashKeyType.getFont().deriveFont((float)13));
        jLabelHashKeyType.setText("--");
        jPanelDetailGraph.add(jLabelHashKeyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 145, 170, 20));

        add(jPanelDetailGraph);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setInputSize(String size) {
        jLabelInputSize.setText(size);
    }

    @Override
    public void setCurrentSize(String currentSize) {

    }

    @Override
    public void setInitialSize(String startSize) {
        jLabelInputSize.setText(startSize);
    }

    @Override
    public void setFinalSize(String startSize) {
        // does nothing
    }

    @Override
    public void setStepSize(String stepSize) {

    }

    @Override
    public void setMemUsage(String memUsage) {

    }

    @Override
    public void setNumCompletedTasks(String numCompletedTasks) {
    }

    @Override
    public void setNumTasks(String numTasks) {

    }

    public void setBucketArraySize(String size) {
        jLabelBucketArraySize.setText(size);
    }

    public void setMinBucketSize(String minSize) {
        jLabelMinBucketSize.setText(minSize);
    }

    public void setMaxBucketSize(String maxSize) {
        jLabelMaxBucketSize.setText(maxSize);
    }

    public void setHashFunctionType(String fType) {
        jLabelHashFunction.setText(fType);
    }

    public void setHashKeyType(String keyType) {
        jLabelHashKeyType.setText(keyType);
    }

    public void setAverageBucketSize(String average) {
        jLabeAverageBucketSize.setText(average);
        //get range too
        Integer range = Integer.parseInt(jLabelMaxBucketSize.getText())
                - Integer.parseInt(jLabelMinBucketSize.getText());
        jLabelBucketSizeRange.setText(range.toString());
    }

    public void setBucketSizeSD(String sd) {
        jLabelBucketSizeSD.setText(sd);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeAverageBucketSize;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabelBucketArraySize;
    private javax.swing.JLabel jLabelBucketSizeRange;
    private javax.swing.JLabel jLabelBucketSizeSD;
    private javax.swing.JLabel jLabelHashFunction;
    private javax.swing.JLabel jLabelHashKeyType;
    private javax.swing.JLabel jLabelInputSize;
    private javax.swing.JLabel jLabelMaxBucketSize;
    private javax.swing.JLabel jLabelMemUsage;
    private javax.swing.JLabel jLabelMinBucketSize;
    private javax.swing.JPanel jPanelDetailGraph;
    private javax.swing.JPanel jPanelGraph;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
